//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPE_High_Speed_Lane_Parser {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class UserProjectSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserProjectSettings defaultInstance = ((UserProjectSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserProjectSettings())));
        
        public static UserProjectSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Cadence\\SPB_17.2\\tools\\bin")]
        public string cadenceToolLocation {
            get {
                return ((string)(this["cadenceToolLocation"]));
            }
            set {
                this["cadenceToolLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P5E")]
        public string pcieNetIdentifier {
            get {
                return ((string)(this["pcieNetIdentifier"]));
            }
            set {
                this["pcieNetIdentifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CLK")]
        public string clockNetIdentifier {
            get {
                return ((string)(this["clockNetIdentifier"]));
            }
            set {
                this["clockNetIdentifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPI")]
        public string upiNetIdentifier {
            get {
                return ((string)(this["upiNetIdentifier"]));
            }
            set {
                this["upiNetIdentifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USB")]
        public string usbNetIdentifier {
            get {
                return ((string)(this["usbNetIdentifier"]));
            }
            set {
                this["usbNetIdentifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_DP")]
        public string positiveDiffPairIdentifier {
            get {
                return ((string)(this["positiveDiffPairIdentifier"]));
            }
            set {
                this["positiveDiffPairIdentifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_DN")]
        public string negativeDiffPairIdentifier {
            get {
                return ((string)(this["negativeDiffPairIdentifier"]));
            }
            set {
                this["negativeDiffPairIdentifier"] = value;
            }
        }
    }
}
